# Generated by Django 4.1.3 on 2022-11-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category_image_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
