# Generated by Django 4.1.3 on 2022-11-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='snippet',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
