# Generated by Django 4.1.3 on 2022-11-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_category_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_header',
            field=models.ImageField(null=True, upload_to='categories/%Y/%m/%d'),
        ),
    ]
