# Generated by Django 4.1.3 on 2022-11-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='is_user',
        ),
        migrations.AddField(
            model_name='bloguser',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
