# Generated by Django 4.1.3 on 2022-11-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_bloguser_is_admin_remove_bloguser_is_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='password_confirm',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
