# Generated by Django 4.1.3 on 2022-11-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bloguser_password_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='password_confirm',
        ),
    ]
