# Generated by Django 4.1.3 on 2022-11-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_bloguser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
    ]
