# Generated by Django 4.1.3 on 2022-11-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_bloguser_is_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/%Y/%m/%d'),
        ),
    ]
