# Generated by Django 4.1.3 on 2022-11-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_author'),
        ('users', '0007_alter_bloguser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='posts',
            field=models.ManyToManyField(null=True, to='posts.post'),
        ),
    ]
