# Generated by Django 4.1.3 on 2022-11-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_author'),
        ('users', '0008_bloguser_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='posts',
            field=models.ManyToManyField(to='posts.post'),
        ),
    ]
