# Generated by Django 4.1.3 on 2022-12-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_bloguser_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
